config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users,
    controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords'
    }

  namespace :admin do
    root to: "dashboard#index"
    resources :banners
    resources :pages
    resources :projects
    resources :articles
    resources :events
    resources :apps
    resources :profile, only: [:edit, :update]
    resources :press_resources
    resources :attachments
    resources :attachment_categories
  end


  namespace :api do

    resources :attachments do
      member do
        get :download
      end
    end

  end
  #end


  resources :pages, only: [:index, :show] do
  #  resources :elements, only: [:create, :update, :destroy]
  end
  resources :projects, only: [:index, :show]
  resources :articles, only: [:index, :show]
  resources :events, only: [:index, :show]
  resources :apps, only: [:index, :show]
  resources :press_resources, only: [:index, :show]
  resources :emblematic_cases, only: [:index, :show]
  resources :attachments, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/views/layouts/shared/_analytics.haml
- if Rails.env.production?
  %script{ async: true, src: 'https://www.googletagmanager.com/gtag/js?id=UA-113130514-1' }
  :javascript
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments)};
    gtag('js', new Date());
    gtag('config', 'UA-122231642-1');

app/views/layouts/shared/_breadcrumb.haml
.breadcrumb
  .container
    = render_breadcrumbs separator: ' / '

app/views/layouts/shared/_footer.html.haml
%footer
  .row
    .small-12.medium-4.columns
      %h2=# Secretaría de Participación, Transparencia y Anticorrupción
      = image_tag("site/spta-s-logo.png")
      %br
      %p
        = "Presidencia de la República<br>Alameda Dr. Enrique Araujo, No. 5500.<br> San Salvador, El Salvador, CA.<br>Tel. +(503)2133-7500 | Email: info@gobiernoabierto.gob.sv".html_safe
      %br
    .small-12.medium-4.columns
      %h3 Suscríbase a nuestro boletín
      = form_tag("//gob.us4.list-manage.com/subscribe/post?u=842a2979e525425004e0dc51b&amp;id=50d05e5605", {class: "navbar-form navbar-left form-inline"}) do
        .input-group
          = hidden_field_tag 'b_842a2979e525425004e0dc51b_50d05e5605', ''

          %input.input-group-field{ type: "text", name: "EMAIL", placeholder: "Correo electrónico" }
            .input-group-button
              %input.button{type: "submit", value: "Suscribirse" }


      .clearfix
      .row
        .medium-6.columns
          = link_to image_tag('site/whatsapp.png', class: "footer-image img-responsive"), "intent://send/77713000#Intent;scheme=smsto;package=com.whatsapp;action=android.intent.action.SENDTO;end"
        .medium-6.columns
          = link_to image_tag('site/phone.png', class: "footer-image img-responsive"), "tel:+50321337500"
      %br
    .small-24.medium-4.columns
      .row
        .medium-6.columns
          %ul
            %li Sobre la secretaría
            %li Descarga y multimedia
            %li Novedades
        .medium-6.columns
          %ul
            %li Casos emblemáticos
            %li Coyunturas
            %li Prensa

app/views/layouts/shared/_header.html.haml
.row
  .medium-24
    .title-bar{class: "hide-for-medium", "data-responsive-toggle" => "main-menu"}
      %button.menu-icon{"data-toggle" => "", :type => "button"}

      .title-bar-title.show-for-small-only
        = link_to image_tag('site/logo.png', class: "logo"), root_url

    #main-menu.top-bar
      .top-bar-left.show-for-medium-only.float-none
        %ul.dropdown.menu{"data-dropdown-menu" => ""}
          %li
            = link_to image_tag('site/logo.png', class: "logo"), root_url

      .top-bar-left.hide-for-medium-only.hide-for-small-only
        %ul.dropdown.menu{"data-dropdown-menu" => ""}
          %li
            = link_to image_tag('site/logo.png', class: "logo"), root_url


      .show-for-medium-only.top-bar-right.float-none
        %ul.header-menu.menu{"data-responsive-menu" => "drilldown medium-dropdown"}
          %li{ class: "#{controller_name == 'pages' ? 'active-option' : ''}"}
            - unless @first_page.nil?
              = link_to @first_page.title, page_url(@first_page)
          %li{ class: "#{controller_name == 'projects' ? 'active-option' : ''}"}
            = link_to "Nuestros proyectos", projects_url()
          -#
            %li.has-submenu
              %a{:href => "#"}
                Nuestros proyectos
              %ul.submenu.menu.vertical{"data-submenu" => ""}
                %li
                  = link_to "Page 1-1", nil
                %li
                  = link_to "Page 1-2", nil
                %li
                  = link_to "Page 1-3", nil

          %li{ class: "#{controller_name == 'articles' ? 'active-option' : ''}" }
            = link_to "Novedades", articles_url()
          %li{ class: "#{controller_name == 'attachments' ? 'active-option' : ''}" }
            = link_to "Informes y estudios", attachments_url()
          %li{ class: "#{controller_name == 'press_resources' ? 'active-option' : ''}" }
            = link_to "Recursos de prensa", press_resources_url()


      .hide-for-medium-only.top-bar-right
        %ul.header-menu.menu{"data-responsive-menu" => "drilldown medium-dropdown"}
          %li{ class: "#{controller_name == 'pages' ? 'active-option' : ''}"}
            - unless @first_page.nil?
              = link_to @first_page.title, page_url(@first_page)
          %li{ class: "#{controller_name == 'projects' ? 'active-option' : ''}"}
            = link_to "Nuestros proyectos", projects_url()
          -#
            %li.has-submenu
              %a{:href => "#"}
                Nuestros proyectos
              %ul.submenu.menu.vertical{"data-submenu" => ""}
                %li
                  = link_to "Page 1-1", nil
                %li
                  = link_to "Page 1-2", nil
                %li
                  = link_to "Page 1-3", nil

          %li{ class: "#{controller_name == 'articles' ? 'active-option' : ''}" }
            = link_to "Novedades", articles_url()
          %li{ class: "#{controller_name == 'attachments' ? 'active-option' : ''}" }
            = link_to "Informes y estudios", attachments_url()
          %li{ class: "#{controller_name == 'press_resources' ? 'active-option' : ''}" }
            = link_to "Recursos de prensa", press_resources_url()

app/views/layouts/shared/_side_content.haml
.wrapper-side
  %h3 Portal de transparencia
  .buttons
    = link_to "Visitar el portal", "http://publica.gobiernoabierto.gob.sv", class: "button"

- if @side_app
  .wrapper-side
    - url = @side_app.url.blank? ? app_path(@side_app) : @side_app.url
    = link_to image_tag(@side_app.image.url(:small)), nil
    %aside
      %span= @side_app.display_kind rescue "Sitio web"
      %h4
        = link_to @side_app.title, url
      %p= @side_app.description
- if @side_article
  .wrapper-side
    - url = @side_article.url.blank? ? app_path(@side_article) : @side_article.url
    = link_to image_tag(@side_article.image.url(:small)), nil
    %aside
      %span= @side_article.display_kind rescue "Artículo"
      %h4
        = link_to @side_article.title, url
      %p= @side_article.description

app/views/layouts/shared/_side_menu.haml
.show-for-small-only
  %ul.vertical.menu.accordion-menu{"data-accordion-menu" => "", "data-submenu-toggle" => "true"}
    - case items.first.class.to_s
      - when "Page"
        - items.each_with_index do |item, i|
          %li
            - if item.pages.size > 0
              = link_to item.title, page_url(item)
              %ul.menu.vertical.nested
                - item.pages.each do |obj|
                  %li
                    = link_to obj.title, page_url(obj)
            - elsif item.pages.size == 0 && item.page_id == nil
              = link_to item.title, page_url(item)
      - when "Project"
        %li
          - items.each_with_index do |item, i|
            = link_to item.title, project_url(item)
      - else
        %li
          = link_to "Noticias", articles_url(), class: "#{controller_name.to_s == 'articles' ? 'not-active' : ''}"
        %li
          = link_to "Eventos", events_url(), class: "#{controller_name.to_s == 'events' ? 'not-active' : ''}"
        -#
          %li
            = link_to "Apps", apps_url(), class: "#{controller_name.to_s == 'apps' ? 'not-active' : ''}"
        %li
          = link_to "Recursos de prensa", press_resources_url(), class: "#{controller_name.to_s == 'press_resources' ? 'not-active' : ''}"
.hide-for-small-only
  %ul.vertical.menu
    - case items.first.class.to_s
      - when "Page"
        - items.each_with_index do |item, i|
          %li
            - if item.pages.size > 0
              = link_to item.title, page_url(item)
              %ul.menu.vertical.nested
                - item.pages.each do |obj|
                  %li
                    = link_to obj.title, page_url(obj)
            - elsif item.pages.size == 0 && item.page_id == nil
              = link_to item.title, page_url(item)
      - when "PressResource"
        %li
          = link_to "Recursos de prensa", press_resources_url(), class: "#{controller_name.to_s == 'press_resources' ? 'not-active' : ''}"

      - when "Project"
        %li
          - items.each_with_index do |item, i|
            = link_to item.title, project_url(item)
      - else
        %li
          = link_to "Noticias", articles_url(), class: "#{controller_name.to_s == 'articles' ? 'not-active' : ''}"
        %li
          = link_to "Eventos", events_url(), class: "#{controller_name.to_s == 'events' ? 'not-active' : ''}"
        -#
          %li
            = link_to "Apps", apps_url(), class: "#{controller_name.to_s == 'apps' ? 'not-active' : ''}"