config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users,
    controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords'
    }

  namespace :admin do
    root to: "dashboard#index"
    resources :banners
    resources :pages
    resources :projects
    resources :articles
    resources :events
    resources :apps
    resources :profile, only: [:edit, :update]
    resources :press_resources
    resources :attachments
    resources :attachment_categories
  end


  namespace :api do

    resources :attachments do
      member do
        get :download
      end
    end

  end
  #end


  resources :pages, only: [:index, :show] do
  #  resources :elements, only: [:create, :update, :destroy]
  end
  resources :projects, only: [:index, :show]
  resources :articles, only: [:index, :show]
  resources :events, only: [:index, :show]
  resources :apps, only: [:index, :show]
  resources :press_resources, only: [:index, :show]
  resources :emblematic_cases, only: [:index, :show]
  resources :attachments, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :attachment_category

  validates :downloads, numericality: { only_integer: true }, allow_nil: true

  has_attached_file :datafile

  has_attached_file :thumbnail,
    content_type: ['image/jpeg', 'image/jpg', 'image/png'],
    styles: { thumb: '120x120>' }

  validates_attachment_content_type :thumbnail, content_type: %r{\Aimage\/.*\Z}

  validates_attachment_presence :datafile


end

app/controllers/admin/attachments_controller.rb
class Admin::AttachmentsController < Admin::ApplicationController
  protect_from_forgery with: :exception, unless: -> { request.format.json? }

  def model
    Attachment
  end

  def index
    @items = model.where(conditions)
    add_breadcrumb model.model_name.human(count: :many), index_url
  end

  def item_params
    params.require(:attachment).permit!
  end

  def create
    @item = model.new item_params
    before_controller_create

    if @item.save
      redirect_to url_for(action: :index), notice: t('layouts.admin.notice.created')
    else
      init_form
      add_breadcrumb model.model_name.human(count: :many), index_url
      add_breadcrumb t('layouts.admin.breadcrumb.new')

      render template: 'concerns/tabled/new'
    end
  end

  def update
    @item = model.find params[:id]
    before_controller_update
    if @item.update_attributes item_params
      redirect_to url_for(action: :index), notice: t('layouts.admin.notice.updated')
    else
      init_form
      add_breadcrumb model.model_name.human(count: :many), index_url
      add_breadcrumb t('layouts.admin.breadcrumb.edit')
      render template: 'concerns/tabled/edit'
    end
  end


end

app/controllers/api/attachments_controller.rb
class Api::AttachmentsController < ApiController

  def download

    if Attachment.exists? params[:id]

      attachment = Attachment.find params[:id]
      attachment.update_attributes(downloads: (attachment.downloads + 1))
      send_file attachment.datafile.path,
                filename: [attachment.name, File.extname(attachment.datafile.path)].join,
                type: attachment.datafile_content_type,
                disposition: 'attachment'
    else
      render_404
    end
  end

end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  include Componentable

  layout 'pages'

  def model
    Attachment
  end

  def index
    @attachment_categories = AttachmentCategory.all
    #@attachments = Attachment.all
  end

  def show
    @attachment_category = AttachmentCategory.find(params[:id])
    @attachments = @attachment_category.attachments
    add_breadcrumb @attachment_category.name, attachment_url(@attachment_category)
  end


    def init_breadcrumb
      super
      add_breadcrumb "Informes y descargas", attachments_url()
    end


end

app/views/attachments/index.html.haml
%section.content
  .row
    .medium-12.columns
      = render partial: 'layouts/shared/breadcrumb'
      .wrapper
        %h2 Informes y estudios
        .report-description
          = "Descargue documentos, informes, convenios nacionales e internacionales, publicaciones y otro material producido desde la Secretaría de Participación, Transparencia y Anticorrupción como una de las políticas que promueve Gobierno Abierto de poner la mayor cantidad de información a disposición de la ciudadanía."
      .wrapper-content
        .row
          .medium-12.columns
            .download-documents
              %h3 Descarga de informes


        .row
          - if @attachment_categories.size > 0
            - @attachment_categories.each_with_index do |category, i|
              .medium-3.columns.attachment-category-wrapper
                = link_to attachment_path(category), class: "category-link" do
                  = image_tag("site/folder.png", class: "centered-folder")
                  = category.name
              - if (i+1) % 4 == 0
                .clearfix
          .clearfix
-#
  .medium-12.columns
    .div-row
      %p
        = image_tag("site/doc.png")
        = link_to attachment.name, attachment.datafile.url
      %p
        = number_to_human_size(attachment.datafile_file_size, precision: 2)
      %p
        = link_to "Descargar", attachment.datafile.url

app/views/attachments/show.html.haml
%section.content
  .row
    .medium-12.columns
      = render partial: 'layouts/shared/breadcrumb'
      .wrapper
        %h2= @attachment_category.name
      .wrapper-content
        - if @attachments && @attachments.size > 0
          .row
            - @attachments.each do |attachment|
              .medium-6.columns
                .div-row
                  %p
                    = image_tag("site/doc.png")
                    = link_to attachment.name, download_api_attachment_url(attachment), target: "_blank"
                  %p
                    = number_to_human_size(attachment.datafile_file_size, precision: 2)
                .attachment-description
                  = attachment.try(:content).html_safe
        - else
          %h5= "No existen documentos"