config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users,
    controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords'
    }

  namespace :admin do
    root to: "dashboard#index"
    resources :banners
    resources :pages
    resources :projects
    resources :articles
    resources :events
    resources :apps
    resources :profile, only: [:edit, :update]
    resources :press_resources
    resources :attachments
    resources :attachment_categories
  end


  namespace :api do

    resources :attachments do
      member do
        get :download
      end
    end

  end
  #end


  resources :pages, only: [:index, :show] do
  #  resources :elements, only: [:create, :update, :destroy]
  end
  resources :projects, only: [:index, :show]
  resources :articles, only: [:index, :show]
  resources :events, only: [:index, :show]
  resources :apps, only: [:index, :show]
  resources :press_resources, only: [:index, :show]
  resources :emblematic_cases, only: [:index, :show]
  resources :attachments, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "application"

  def index
    @banner = Banner.where(active: true).first
    @articles = Article.where(feature: 1, active: 1, kind: "article").limit(3)
    @projects = Project.where(feature: 1, active: 1).limit(3)
    @emblematic_case = Article.where(feature: 1, active: 1, kind: "emblematic").first
    @attachment = Attachment.last
    @app = App.first
    @press_resource = PressResource.last rescue nil
  end

end

app/views/home/index.html.haml
- unless @banner.blank?
  %header{class: "header-bg", style: "background-image: url(#{asset_path(@banner.image.url)});"}
    = render partial: 'layouts/shared/header'
    .clearfix
      .row.banner
        .medium-7.medium-offset-5.large-6.large-offset-6.columns
          .banner-description
            %h1
              = @banner.title
            %br
            - if @banner.radio_stream == true
              .audio-js-box.hu-css
                / Using the Audio for Everybody Embed Code http://camendesign.com/code/audio_for_everybody
                %audio.audio-js{:controls => "", :preload => ""}
                  %source{:src => @banner.url}

            - else
              = link_to @banner.description, @banner.url, class: "btn-transparent", target: "_blank"

-#
  %section.news
    .row
      .medium-12
        %h2 CONVOCATORIA
    .row
      .medium-12.columns
        .center-div
          = image_tag("admin/convocatoria.jpg")
      .row
        .medium-12.columns
          .more-news
            = link_to "Descargar términos", "https://www.spta.gob.sv/api/attachments/13/download", class: "button", target: "_blank"


- if @articles.size > 0
  %section.news
    .row
      .medium-12
        %h2 NOVEDADES
    - if @articles.size > 0
      .row
        - @articles.each_with_index do |article, i|
          - url = article.url.blank? ? article_path(article) : article.url
          .small-12.medium-6.large-4.columns{class: "#{i==@articles.size-1 ? 'end' : ''}"}
            .news-image
              = link_to image_tag(article.image.url(:medium)), url rescue link_to image_tag("site/ga.png"), url
              %span
                = article.published_at.strftime("%d %b %Y")
            .news-content
              %span= article.display_kind rescue "Artículo"
              %h3
                = link_to url do
                  = truncate(article.title, length: 80, omission: '...')
              %p
                = truncate(article.description, length: 140, omission: '...')
      .row
        .medium-12.columns
          .more-news
            = link_to "Más novedades", articles_url, class: "button"
- if @projects.size > 0
  %section.projects
    .row
      .large-12.medium-12.small-12.columns
        %h2 NUESTROS PROYECTOS
        %br
        .projects-wrapper
          - @projects.each_with_index do |project, i|
            .project
              = link_to image_tag(project.image.url(:medium)), project_url(project) rescue link_to image_tag("site/fotos-08.png"), project_url(project)
              .title-project
                %h3
                  = link_to project_url(project) do
                    = project.title
              %p
                = truncate(project.description, length: 100, omission: '...')

        .clearfix
    .clearfix
    %br
    .row
      .medium-12.columns
        .more-projects
          = link_to "Más proyectos", projects_url, class: "button white-button"
%section.info
  - unless @emblematic_case.blank?
    .row
      .small-12.medium-6.columns
        %h2 Coyunturas claras
        %span
          = @emblematic_case.published_at.strftime("%d %b %Y")
        %h3
          = @emblematic_case.title
        %p
          = truncate(@emblematic_case.description, length: 300, omission: '...')
        .buttons
          = link_to "Leer artículos", nil, class: "button"
          = link_to "Listado completo de artículos", nil, class: "hollow button"

      .small-12.medium-6.columns
        .info-image
          = link_to image_tag('site/fotos-03.png'), nil

  - unless @app.blank?
    .row
      .small-12.medium-6.medium-push-6.columns
        %h2 APPS
        %span
          = @app.published_at.strftime("%d %b %Y")
        %h3
          = @app.title
        %p
          = truncate(@app.description, length: 300, omission: '...')
        .buttons
          = link_to "Ver APP", nil, class: "button"
          = link_to "Listado completo de APPS", nil, class: "hollow button"
      .small-12.medium-6.medium-pull-6.columns
        .info-image
          = link_to image_tag('site/apps.jpg'), nil
%section.resources
  .row
    .small-12.medium-6.columns.reports
      %h2 Descarga de informes
      .row
        .small-3.small-offset-1.columns
          = image_tag("site/doc1.png")
        .small-8.columns
          %span
            = @attachment.created_at.strftime("%d %b %Y")
          .title-resource
            %h3
              = @attachment.name
          .buttons
            = link_to "Descargar", @attachment.datafile.url, target: "_blank", class: "button white-button"
            = link_to "Ver listado completo", attachments_url, class: "button hollow-white-button"

    - if @press_resource
      .small-12.medium-6.columns.press
        %h2 Recursos para prensa
        .row
          .small-3.small-offset-1.columns
            = image_tag("site/doc2.png")
          .small-8.columns
            %span
              = @press_resource.created_at.strftime("%d %b %Y")
            .title-resource
              %h3
                = @press_resource.title
            .buttons
              = link_to "Descargar", press_resource_url(@press_resource), class: "button white-button"
              = link_to "Ver listado completo", press_resources_url, class: "button hollow-white-button"